import type { Snapshot } from "./types";
const now = Date.now();
const agent = (
  id: string,
  name: string,
  role: string,
  task: string,
  state: string,
  tool: string,
  model: string,
  inputTokens: number,
  outputTokens: number,
  cost: number,
) => ({
  id,
  name,
  role,
  task,
  state,
  tool,
  model,
  inputTokens,
  outputTokens,
  cost,
  updatedAt: now,
  logs: [
    { time: now - 45000, level: "info", message: "Agent joined this session" },
    { time: now - 30000, level: "info", message: task },
    {
      time: now - 4000,
      level: state === "error" ? "error" : "tool",
      message: tool
        ? `Observing ${tool}`
        : "Turn complete. Waiting for the next task.",
    },
  ],
});
export const demo: Snapshot = {
  updatedAt: now,
  sessions: [
    {
      id: "demo-web",
      name: "Website redesign",
      cwd: "C:\\work\\northstar-web",
      model: "claude-sonnet-4-5",
      agents: [
        agent(
          "web-lead",
          "Atlas",
          "Lead agent",
          "Coordinate the new product experience",
          "thinking",
          "Planning next step",
          "claude-sonnet-4-5",
          42800,
          8600,
          0.29,
        ),
        agent(
          "web-ui",
          "Nova",
          "Frontend",
          "Build the settings experience",
          "working",
          "edit · src/settings.tsx",
          "claude-sonnet-4-5",
          24100,
          6200,
          0.17,
        ),
        agent(
          "web-tests",
          "Scout",
          "QA & testing",
          "Verify checkout edge cases",
          "working",
          "bash · npm test",
          "claude-sonnet-4-5",
          18700,
          3900,
          0.12,
        ),
        agent(
          "web-review",
          "Sage",
          "Code review",
          "Review accessibility changes",
          "completed",
          "",
          "claude-sonnet-4-5",
          12300,
          2100,
          0.07,
        ),
      ],
    },
    {
      id: "demo-api",
      name: "API migration",
      cwd: "C:\\work\\platform-api",
      model: "gpt-5",
      agents: [
        agent(
          "api-lead",
          "Orion",
          "Lead agent",
          "Migrate the billing endpoints",
          "working",
          "read · billing/router.ts",
          "gpt-5",
          31700,
          7100,
          0.23,
        ),
        agent(
          "api-data",
          "Fern",
          "Data & schemas",
          "Validate the new account schema",
          "waiting",
          "",
          "gpt-5",
          16400,
          2700,
          0.11,
        ),
        agent(
          "api-docs",
          "Echo",
          "Documentation",
          "Update the API migration guide",
          "idle",
          "",
          "gpt-5",
          8200,
          1400,
          0.04,
        ),
      ],
    },
  ],
};
